spring:
  application:
    name: crud-example
  datasource:
    url: jdbc:h2:~/rms
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    format_sql: true
    hibernate:
      ddl_auto: create-drop
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  h2:
    console:
      enabled: true
server:
  port: 8081